[package]
name = "reka"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "reka - Emacs-based river WM"

[lib]
name = "reka"
path = "src/lib.rs"
crate-type = [ "cdylib" ]

[dependencies]
anyhow = "1.0.102"
bitflags = "2.11"
emacs = { version = "0.21.0", features = ["emacs-28"] }
env_logger = "0.11.9"
log = "0.4.29"
nix = { version = "0.31.1", features = ["event", "signal"] }
wayland-backend = "0.3.12"
wayland-client = "0.31.12"
wayland-scanner = "0.31.8"
xkbcommon = "0.9"
