* Râu - Wayland Window Manager in Emacs

Râu is written entirely in Elisp, even the communication with the wayland
socket. External (to Emacs) Wayland Windows feel like Emacs buffers. Thus an
Emacs user can use the already known keybindings and mechanisms from Emacs
to manage windows.

See [[rau.org]] for more information.

** How does it work?

Every output (screen, monitor) gets one fullscreen Emacs frame assigned that
stays in the background. Every external Wayland Window gets one Emacs buffer
assigned. When this buffer is displayed, the external Wayland Window for this
buffer gets displayed exactly on top of the buffer.

** Status

I already use Râu however there are still some issues:

- Every other day there is an endless loop of keypresses and I have to switch
  to a tty and back to stop it.
- Only minimal support for floating windows: no move, resize or minimize.
- No protection against accidental closing of Emacs, just one C-x C-c away.
- Tab titles don't get updated when in background.
- Clicking on a x-popup-menu or x-popup-dialog (e.g. from flyspell) freezes
  Râu and Emacs needs to be restarted.

** Roadmap

- Get it into Melpa.
- Try to do socket communication in a separate thread in a dynamic module to
  avoid deadlocks in x-popup-menu.
- Performance, this might fix the endless keypress loops.
- avoid user accidentally closing emacs, e.g. with confirm-kill-emacs
- smaller reconcile functions that check whether requests should be sent

*** Ideas

- https://joshblais.com/blog/i-built-a-launcher-in-emacs/
- Try filechooser.el https://codeberg.org/rahguzar/filechooser/pulls/23

** Name

"Râu" means "River" in Romanian and is not to be confused with "rău" meaning
"bad", "vile" or "vicious" nor with the German word "rau" meaning "rough", "harsh" or "raw".

** Acknowledgements

- Michael Bauer for the [[http://perma-curious.eu/repo-ewx/][Emacs Wayland Client]], presented at [[https://emacsconf.org/2022/talks/wayland/][EmacsConf 2022]].
- Tazjin for [[https://codeberg.org/tazjin/reka][Reka]], predecessor of Râu, which however used Rust to bind to libwayland.
- Isaac Freund for [[https://isaacfreund.com/software/river/][River]], which makes writing a Wayland WM very easy.

** Alternatives

Check the category [[https://www.emacswiki.org/emacs/CategoryWindowManager][Window Manager]] in the Emacs Wiki for alternatives to Râu.

